### ISSUE TITLE
Better error message for invalid Cipher Key

### ISSUE THREAD

**Issue by etsuo** [sakuraapi/auth-native-authority#9]
This is misleading. The key does not need to be a buffer... it can be a string... it can't be null or undefined.
```
TypeError: Key must be a buffer
    at new Cipheriv (crypto.js:217:16)
    at Object.Cipheriv (crypto.js:215:12)
    at Promise (/Users/jpoveda/dev/olive/seedCompany/illuminations/ilb-profile-server/node_modules/@sakuraapi/auth-native-authority/src/authentication.ts:861:26)
    at Promise (<anonymous>)
    at AuthenticationAuthorityApi.encryptToken (/Users/jpoveda/dev/olive/seedCompany/illuminations/ilb-profile-server/node_modules/@sakuraapi/auth-native-authority/src/authentication.ts:858:14)
    at User.getOne.then.then.then.then.then (/Users/jpoveda/dev/olive/seedCompany/illuminations/ilb-profile-server/node_modules/@sakuraapi/auth-native-authority/src/authentication.ts:579:26)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by etsuo** [comment]
resolved in #15
